import React, { useState } from 'react';
import { 
  X, Bot, Sparkles, CheckCircle2, Play, Pause, Volume2, Share2, 
  Rss, MessageCircle, Send, Cpu, Radio, ShieldCheck, Zap, Layers, BarChart2, Video
} from 'lucide-react';
import { AutonomousNewsroomEngine, AutonomousArticleDraft } from '../services/AutonomousNewsroomEngine';
import { MultimediaProductionEngine, AudioVoiceProfile, PodcastEpisode } from '../services/MultimediaProductionEngine';
import { SyndicationService, SyndicationChannel, BroadcastLog } from '../services/SyndicationService';

interface AutonomousNewsroomModalProps {
  onClose: () => void;
}

export const AutonomousNewsroomModal: React.FC<AutonomousNewsroomModalProps> = ({ onClose }) => {
  const [activeTab, setActiveTab] = useState<'overview' | 'content_studio' | 'multimedia' | 'syndication'>('overview');
  
  // Data State
  const [drafts, setDrafts] = useState<AutonomousArticleDraft[]>(AutonomousNewsroomEngine.getDrafts());
  const [podcasts, setPodcasts] = useState<PodcastEpisode[]>(MultimediaProductionEngine.getPodcasts());
  const [channels, setChannels] = useState<SyndicationChannel[]>(SyndicationService.getChannels());
  const [logs, setLogs] = useState<BroadcastLog[]>(SyndicationService.getLogs());

  // Form Inputs
  const [newTopic, setNewTopic] = useState('');
  const [newCategory, setNewCategory] = useState('Technology');
  const [selectedVoiceId, setSelectedVoiceId] = useState('voice-1');
  const [podTitleInput, setPodTitleInput] = useState('');
  const [podSummaryInput, setPodSummaryInput] = useState('');

  // Audio Playback Simulation State
  const [playingPodcastId, setPlayingPodcastId] = useState<string | null>(null);
  const [isPlaying, setIsPlaying] = useState<boolean>(false);
  const [toastMessage, setToastMessage] = useState<string | null>(null);

  const metrics = AutonomousNewsroomEngine.getMetrics();
  const voiceProfiles = MultimediaProductionEngine.getVoiceProfiles();

  const showToast = (msg: string) => {
    setToastMessage(msg);
    setTimeout(() => setToastMessage(null), 3000);
  };

  const handleCreateDraft = (e: React.FormEvent) => {
    e.preventDefault();
    if (!newTopic.trim()) return;

    const draft = AutonomousNewsroomEngine.generateAutonomousDraft(newTopic, newCategory);
    setDrafts([...AutonomousNewsroomEngine.getDrafts()]);
    setNewTopic('');
    showToast(`AI Autonomous Draft generated: "${draft.title}" with ${draft.verificationScore}% verification score.`);
  };

  const handlePublishDraft = (id: string) => {
    const published = AutonomousNewsroomEngine.approveAndPublish(id);
    if (published) {
      setDrafts([...AutonomousNewsroomEngine.getDrafts()]);
      // Also broadcast
      SyndicationService.triggerMultiChannelBroadcast(published.title);
      setLogs([...SyndicationService.getLogs()]);
      showToast(`Article "${published.title}" published & syndicated to multi-channels.`);
    }
  };

  const handleGeneratePodcast = (e: React.FormEvent) => {
    e.preventDefault();
    if (!podTitleInput.trim()) return;

    const pod = MultimediaProductionEngine.generatePodcast(
      podTitleInput,
      podSummaryInput || 'Automated audio intelligence broadcast generated by Veritas AI Voice Synthesizer.',
      selectedVoiceId
    );
    setPodcasts([...MultimediaProductionEngine.getPodcasts()]);
    setPodTitleInput('');
    setPodSummaryInput('');
    showToast(`Podcast episode synthesized: "${pod.title}"`);
  };

  const togglePlayAudio = (pod: PodcastEpisode) => {
    if (playingPodcastId === pod.id && isPlaying) {
      setIsPlaying(false);
      setPlayingPodcastId(null);
      if ('speechSynthesis' in window) window.speechSynthesis.cancel();
    } else {
      if ('speechSynthesis' in window) window.speechSynthesis.cancel();
      setPlayingPodcastId(pod.id);
      setIsPlaying(true);

      if ('speechSynthesis' in window) {
        const utterance = new SpeechSynthesisUtterance(pod.transcript);
        utterance.onend = () => {
          setIsPlaying(false);
          setPlayingPodcastId(null);
        };
        window.speechSynthesis.speak(utterance);
      }
    }
  };

  const handleBroadcastAll = () => {
    const latestPublished = drafts.find(d => d.status === 'PUBLISHED') || drafts[0];
    const newLogs = SyndicationService.triggerMultiChannelBroadcast(latestPublished.title);
    setLogs([...SyndicationService.getLogs()]);
    setChannels([...SyndicationService.getChannels()]);
    showToast(`Multi-channel broadcast completed across ${newLogs.length} enterprise endpoints.`);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/80 backdrop-blur-md p-4 overflow-y-auto">
      <div className="bg-slate-900 border border-slate-800 text-slate-100 rounded-3xl w-full max-w-6xl max-h-[92vh] flex flex-col shadow-2xl overflow-hidden font-sans">
        
        {/* Header */}
        <div className="px-6 py-4 bg-slate-950 border-b border-slate-800 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="p-2.5 bg-indigo-500/10 border border-indigo-500/30 rounded-2xl text-indigo-400">
              <Bot className="w-6 h-6 animate-pulse" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h2 className="text-xl font-extrabold text-white tracking-tight">Autonomous AI Newsroom Studio</h2>
                <span className="px-2.5 py-0.5 bg-emerald-500/10 text-emerald-400 border border-emerald-500/30 rounded-full text-[10px] font-bold uppercase tracking-wider flex items-center gap-1">
                  <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 animate-ping"></span> Live Phase 7 Active
                </span>
              </div>
              <p className="text-xs text-slate-400">
                Automated Content Generation, AI Fact-Verification, Voice Podcast Studio & Multi-Channel Syndication
              </p>
            </div>
          </div>

          <button 
            onClick={onClose}
            className="p-2 text-slate-400 hover:text-white hover:bg-slate-800 rounded-xl transition-all cursor-pointer"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Navigation Tabs */}
        <div className="px-6 py-3 bg-slate-900 border-b border-slate-800 flex items-center justify-between flex-wrap gap-2">
          <div className="flex items-center gap-2 overflow-x-auto no-scrollbar">
            <button
              onClick={() => setActiveTab('overview')}
              className={`px-4 py-2 rounded-xl text-xs font-bold transition-all flex items-center gap-2 cursor-pointer ${
                activeTab === 'overview' ? 'bg-indigo-600 text-white shadow-lg shadow-indigo-600/30' : 'text-slate-400 hover:text-white hover:bg-slate-800/60'
              }`}
            >
              <Cpu className="w-4 h-4" /> AI Operations & Telemetry
            </button>
            <button
              onClick={() => setActiveTab('content_studio')}
              className={`px-4 py-2 rounded-xl text-xs font-bold transition-all flex items-center gap-2 cursor-pointer ${
                activeTab === 'content_studio' ? 'bg-indigo-600 text-white shadow-lg shadow-indigo-600/30' : 'text-slate-400 hover:text-white hover:bg-slate-800/60'
              }`}
            >
              <Sparkles className="w-4 h-4" /> Autonomous Content Studio
            </button>
            <button
              onClick={() => setActiveTab('multimedia')}
              className={`px-4 py-2 rounded-xl text-xs font-bold transition-all flex items-center gap-2 cursor-pointer ${
                activeTab === 'multimedia' ? 'bg-indigo-600 text-white shadow-lg shadow-indigo-600/30' : 'text-slate-400 hover:text-white hover:bg-slate-800/60'
              }`}
            >
              <Volume2 className="w-4 h-4" /> Voice Podcast & Audio Studio
            </button>
            <button
              onClick={() => setActiveTab('syndication')}
              className={`px-4 py-2 rounded-xl text-xs font-bold transition-all flex items-center gap-2 cursor-pointer ${
                activeTab === 'syndication' ? 'bg-indigo-600 text-white shadow-lg shadow-indigo-600/30' : 'text-slate-400 hover:text-white hover:bg-slate-800/60'
              }`}
            >
              <Share2 className="w-4 h-4" /> Multi-Channel Syndication
            </button>
          </div>

          <div className="flex items-center gap-2">
            <button 
              onClick={handleBroadcastAll}
              className="px-3.5 py-1.5 bg-emerald-600 hover:bg-emerald-500 text-white rounded-xl text-xs font-bold transition-all shadow-md flex items-center gap-1.5 cursor-pointer"
            >
              <Radio className="w-3.5 h-3.5 animate-pulse" /> Trigger Live Syndication
            </button>
          </div>
        </div>

        {/* Toast Alert */}
        {toastMessage && (
          <div className="mx-6 mt-4 p-3 bg-emerald-950/80 border border-emerald-500/50 text-emerald-300 rounded-xl text-xs flex items-center gap-2 shadow-lg">
            <CheckCircle2 className="w-4 h-4 shrink-0" />
            <span>{toastMessage}</span>
          </div>
        )}

        {/* Modal Body */}
        <div className="p-6 flex-1 overflow-y-auto space-y-6">

          {/* TAB 1: OVERVIEW */}
          {activeTab === 'overview' && (
            <div className="space-y-6">
              {/* Telemetry Stats Banner */}
              <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-4">
                <div className="p-4 bg-slate-950 border border-slate-800 rounded-2xl space-y-1">
                  <span className="text-[10px] text-slate-400 font-bold uppercase tracking-wider block">Auto-Published Articles</span>
                  <div className="flex items-baseline gap-2">
                    <span className="text-2xl font-black text-white">{metrics.totalAutoPublished}</span>
                    <span className="text-[10px] text-emerald-400 font-semibold">+12 today</span>
                  </div>
                  <span className="text-[10px] text-slate-500 block">Verified & Distributed</span>
                </div>

                <div className="p-4 bg-slate-950 border border-slate-800 rounded-2xl space-y-1">
                  <span className="text-[10px] text-slate-400 font-bold uppercase tracking-wider block">Avg Verification Score</span>
                  <div className="flex items-baseline gap-2">
                    <span className="text-2xl font-black text-emerald-400">{metrics.averageVerificationScore}%</span>
                    <span className="text-[10px] text-slate-400">Trust Matrix</span>
                  </div>
                  <span className="text-[10px] text-slate-500 block">Zero Critical Misinformation</span>
                </div>

                <div className="p-4 bg-slate-950 border border-slate-800 rounded-2xl space-y-1">
                  <span className="text-[10px] text-slate-400 font-bold uppercase tracking-wider block">Speed to Publish</span>
                  <div className="flex items-baseline gap-2">
                    <span className="text-2xl font-black text-indigo-400">{metrics.avgSpeedToPublishSeconds}s</span>
                    <span className="text-[10px] text-slate-400">Ingestion → Live</span>
                  </div>
                  <span className="text-[10px] text-slate-500 block">Autonomous Benchmark</span>
                </div>

                <div className="p-4 bg-slate-950 border border-slate-800 rounded-2xl space-y-1">
                  <span className="text-[10px] text-slate-400 font-bold uppercase tracking-wider block">Active AI Agents</span>
                  <div className="flex items-baseline gap-2">
                    <span className="text-2xl font-black text-cyan-400">{metrics.activeAgents}</span>
                    <span className="text-[10px] text-slate-400">Agents Online</span>
                  </div>
                  <span className="text-[10px] text-slate-500 block">Draft, FactCheck, Voice, Sync</span>
                </div>
              </div>

              {/* Roster of Autonomous Agents */}
              <div className="p-6 bg-slate-950 border border-slate-800 rounded-2xl space-y-4">
                <div className="flex items-center justify-between">
                  <div>
                    <h3 className="text-sm font-bold text-white flex items-center gap-2">
                      <Bot className="w-4 h-4 text-indigo-400" /> Active Autonomous Newsroom AI Roster
                    </h3>
                    <p className="text-xs text-slate-400">Specialized agents performing continuous news synthesis and verification</p>
                  </div>
                  <span className="px-2.5 py-1 bg-indigo-500/10 text-indigo-400 rounded-lg text-xs font-bold border border-indigo-500/20">
                    ALL SYSTEMS NOMINAL
                  </span>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
                  <div className="p-4 bg-slate-900 border border-slate-800 rounded-xl space-y-2">
                    <div className="flex items-center justify-between">
                      <span className="font-bold text-xs text-white flex items-center gap-1.5">
                        <Sparkles className="w-3.5 h-3.5 text-amber-400" /> Drafting Agent Alpha
                      </span>
                      <span className="w-2 h-2 rounded-full bg-emerald-400"></span>
                    </div>
                    <p className="text-[11px] text-slate-400">Crawls verified wire services and generates raw structured drafts.</p>
                    <div className="text-[10px] text-indigo-400 font-mono">Tasks Completed: 1,420</div>
                  </div>

                  <div className="p-4 bg-slate-900 border border-slate-800 rounded-xl space-y-2">
                    <div className="flex items-center justify-between">
                      <span className="font-bold text-xs text-white flex items-center gap-1.5">
                        <ShieldCheck className="w-3.5 h-3.5 text-emerald-400" /> FactCheck Matrix
                      </span>
                      <span className="w-2 h-2 rounded-full bg-emerald-400"></span>
                    </div>
                    <p className="text-[11px] text-slate-400">Cross-references satellite telemetry and primary source documents.</p>
                    <div className="text-[10px] text-emerald-400 font-mono">Precision: 99.4%</div>
                  </div>

                  <div className="p-4 bg-slate-900 border border-slate-800 rounded-xl space-y-2">
                    <div className="flex items-center justify-between">
                      <span className="font-bold text-xs text-white flex items-center gap-1.5">
                        <Volume2 className="w-3.5 h-3.5 text-cyan-400" /> Voice Audio Producer
                      </span>
                      <span className="w-2 h-2 rounded-full bg-emerald-400"></span>
                    </div>
                    <p className="text-[11px] text-slate-400">Converts verified articles into multi-lingual audio podcasts.</p>
                    <div className="text-[10px] text-cyan-400 font-mono">Voices Active: 3</div>
                  </div>

                  <div className="p-4 bg-slate-900 border border-slate-800 rounded-xl space-y-2">
                    <div className="flex items-center justify-between">
                      <span className="font-bold text-xs text-white flex items-center gap-1.5">
                        <Radio className="w-3.5 h-3.5 text-indigo-400" /> Multi-Channel Dispatch
                      </span>
                      <span className="w-2 h-2 rounded-full bg-emerald-400"></span>
                    </div>
                    <p className="text-[11px] text-slate-400">Syndicates outputs to WhatsApp, RSS, Webhooks, and Social.</p>
                    <div className="text-[10px] text-indigo-400 font-mono">Endpoints: 5</div>
                  </div>
                </div>
              </div>
            </div>
          )}

          {/* TAB 2: AUTONOMOUS CONTENT STUDIO */}
          {activeTab === 'content_studio' && (
            <div className="space-y-6">
              {/* Form to trigger new autonomous article */}
              <div className="p-6 bg-slate-950 border border-slate-800 rounded-2xl space-y-4">
                <h3 className="text-sm font-bold text-white flex items-center gap-2">
                  <Sparkles className="w-4 h-4 text-indigo-400" /> Autonomous Article Draft Generator
                </h3>
                
                <form onSubmit={handleCreateDraft} className="grid grid-cols-1 md:grid-cols-3 gap-4">
                  <div className="md:col-span-2">
                    <label className="text-xs text-slate-400 font-semibold block mb-1">Target Intelligence Subject / Wire Breaking Event</label>
                    <input 
                      type="text"
                      placeholder="e.g. Subsea Telecom Cable Monitoring in South China Sea"
                      value={newTopic}
                      onChange={(e) => setNewTopic(e.target.value)}
                      className="w-full px-3.5 py-2 bg-slate-900 border border-slate-800 rounded-xl text-xs text-white focus:outline-none focus:border-indigo-500"
                    />
                  </div>

                  <div>
                    <label className="text-xs text-slate-400 font-semibold block mb-1">Category Domain</label>
                    <div className="flex gap-2">
                      <select
                        value={newCategory}
                        onChange={(e) => setNewCategory(e.target.value)}
                        className="w-full px-3.5 py-2 bg-slate-900 border border-slate-800 rounded-xl text-xs text-white focus:outline-none focus:border-indigo-500"
                      >
                        <option value="Technology">Technology & AI</option>
                        <option value="Geopolitics">Geopolitics & Defense</option>
                        <option value="Energy & Climate">Energy & Climate</option>
                        <option value="Finance">Markets & Economy</option>
                      </select>
                      <button
                        type="submit"
                        className="px-4 py-2 bg-indigo-600 hover:bg-indigo-500 text-white rounded-xl text-xs font-bold transition-all shrink-0 cursor-pointer"
                      >
                        Auto-Generate
                      </button>
                    </div>
                  </div>
                </form>
              </div>

              {/* Drafts List */}
              <div className="space-y-4">
                <h3 className="text-sm font-bold text-white">Autonomous Draft Pipeline ({drafts.length})</h3>

                <div className="space-y-4">
                  {drafts.map(d => (
                    <div key={d.id} className="p-5 bg-slate-950 border border-slate-800 rounded-2xl space-y-3">
                      <div className="flex flex-col md:flex-row md:items-center justify-between gap-2">
                        <div className="flex items-center gap-2">
                          <span className={`px-2.5 py-0.5 rounded text-[10px] font-bold uppercase ${
                            d.status === 'PUBLISHED' ? 'bg-emerald-500/10 text-emerald-400 border border-emerald-500/30' :
                            d.status === 'READY_FOR_PUBLISH' ? 'bg-indigo-500/10 text-indigo-400 border border-indigo-500/30' :
                            'bg-amber-500/10 text-amber-400 border border-amber-500/30'
                          }`}>
                            {d.status}
                          </span>
                          <span className="text-xs font-semibold text-slate-400">{d.category}</span>
                          <span className="text-[10px] text-slate-500">• Ingested: {new Date(d.createdAt).toLocaleTimeString()}</span>
                        </div>

                        <div className="flex items-center gap-3">
                          <span className="text-xs text-emerald-400 font-mono font-bold">
                            Verification: {d.verificationScore}%
                          </span>
                          {d.status !== 'PUBLISHED' && (
                            <button
                              onClick={() => handlePublishDraft(d.id)}
                              className="px-3 py-1 bg-emerald-600 hover:bg-emerald-500 text-white rounded-lg text-xs font-bold transition-all cursor-pointer"
                            >
                              Approve & Publish
                            </button>
                          )}
                        </div>
                      </div>

                      <h4 className="text-base font-bold text-white">{d.title}</h4>
                      <p className="text-xs text-slate-300 leading-relaxed">{d.content}</p>

                      {/* Multi-Format Output Cards */}
                      <div className="pt-2 grid grid-cols-1 md:grid-cols-3 gap-3">
                        <div className="p-3 bg-slate-900 border border-slate-800/80 rounded-xl space-y-1">
                          <span className="text-[10px] font-bold text-indigo-400 uppercase tracking-wider block">Executive Briefing</span>
                          <p className="text-[11px] text-slate-300 italic">{d.formats.executiveBrief}</p>
                        </div>

                        <div className="p-3 bg-slate-900 border border-slate-800/80 rounded-xl space-y-1">
                          <span className="text-[10px] font-bold text-emerald-400 uppercase tracking-wider block">WhatsApp Card</span>
                          <p className="text-[11px] text-slate-300">{d.formats.whatsAppCard}</p>
                        </div>

                        <div className="p-3 bg-slate-900 border border-slate-800/80 rounded-xl space-y-1">
                          <span className="text-[10px] font-bold text-cyan-400 uppercase tracking-wider block">Audio Script Teaser</span>
                          <p className="text-[11px] text-slate-300">{d.formats.audioScript}</p>
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          )}

          {/* TAB 3: MULTIMEDIA & AUDIO PODCAST STUDIO */}
          {activeTab === 'multimedia' && (
            <div className="space-y-6">
              {/* Voice Profile Selector & Podcast Synthesizer Form */}
              <div className="p-6 bg-slate-950 border border-slate-800 rounded-2xl space-y-4">
                <h3 className="text-sm font-bold text-white flex items-center gap-2">
                  <Volume2 className="w-4 h-4 text-cyan-400" /> AI Podcast Voice Synthesizer Studio
                </h3>

                <form onSubmit={handleGeneratePodcast} className="space-y-4">
                  <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                    {voiceProfiles.map(v => (
                      <div 
                        key={v.id}
                        onClick={() => setSelectedVoiceId(v.id)}
                        className={`p-3.5 rounded-xl border cursor-pointer transition-all space-y-1 ${
                          selectedVoiceId === v.id 
                            ? 'bg-indigo-950/60 border-indigo-500/80 text-white shadow-md' 
                            : 'bg-slate-900 border-slate-800 text-slate-400 hover:border-slate-700'
                        }`}
                      >
                        <div className="flex items-center justify-between">
                          <span className="font-bold text-xs text-white">{v.name}</span>
                          <span className="text-[10px] text-indigo-400 font-mono">{v.accent}</span>
                        </div>
                        <p className="text-[11px] text-slate-300">{v.role}</p>
                        <div className="text-[10px] text-slate-500">Pitch: {v.pitch}x • Speed: {v.speed}x</div>
                      </div>
                    ))}
                  </div>

                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div>
                      <label className="text-xs text-slate-400 font-semibold block mb-1">Podcast Episode Title</label>
                      <input 
                        type="text"
                        placeholder="e.g. Geopolitical Risk Briefing: Red Sea Telemetry"
                        value={podTitleInput}
                        onChange={(e) => setPodTitleInput(e.target.value)}
                        className="w-full px-3.5 py-2 bg-slate-900 border border-slate-800 rounded-xl text-xs text-white focus:outline-none focus:border-indigo-500"
                      />
                    </div>
                    <div>
                      <label className="text-xs text-slate-400 font-semibold block mb-1">Summary / Context</label>
                      <input 
                        type="text"
                        placeholder="Key briefing points for the synthesized voice anchor..."
                        value={podSummaryInput}
                        onChange={(e) => setPodSummaryInput(e.target.value)}
                        className="w-full px-3.5 py-2 bg-slate-900 border border-slate-800 rounded-xl text-xs text-white focus:outline-none focus:border-indigo-500"
                      />
                    </div>
                  </div>

                  <button
                    type="submit"
                    className="w-full py-2.5 bg-indigo-600 hover:bg-indigo-500 text-white rounded-xl text-xs font-bold transition-all shadow-md flex items-center justify-center gap-2 cursor-pointer"
                  >
                    <Sparkles className="w-4 h-4" /> Synthesize & Render AI Audio Podcast Episode
                  </button>
                </form>
              </div>

              {/* Podcasts List */}
              <div className="space-y-4">
                <h3 className="text-sm font-bold text-white">Synthesized Audio Episodes ({podcasts.length})</h3>

                <div className="space-y-3">
                  {podcasts.map(pod => (
                    <div key={pod.id} className="p-4 bg-slate-950 border border-slate-800 rounded-2xl space-y-3">
                      <div className="flex flex-col md:flex-row md:items-center justify-between gap-3">
                        <div className="flex items-center gap-3">
                          <button
                            onClick={() => togglePlayAudio(pod)}
                            className={`p-3 rounded-xl transition-all cursor-pointer ${
                              playingPodcastId === pod.id && isPlaying 
                                ? 'bg-amber-500 text-slate-950 shadow-lg' 
                                : 'bg-indigo-600 text-white hover:bg-indigo-500'
                            }`}
                          >
                            {playingPodcastId === pod.id && isPlaying ? <Pause className="w-5 h-5" /> : <Play className="w-5 h-5 fill-current" />}
                          </button>
                          <div>
                            <h4 className="text-sm font-bold text-white">{pod.title}</h4>
                            <p className="text-xs text-slate-400">{pod.summary}</p>
                          </div>
                        </div>

                        <div className="flex items-center gap-3 text-xs text-slate-400">
                          <span className="font-mono text-indigo-400">Voice: {pod.voiceProfile.name} ({pod.voiceProfile.role})</span>
                          <span>• {Math.floor(pod.durationSeconds / 60)}m {pod.durationSeconds % 60}s</span>
                        </div>
                      </div>

                      {/* Waveform Telemetry Visualizer */}
                      <div className="p-2.5 bg-slate-900 rounded-xl flex items-end gap-1 h-12">
                        {pod.audioWaveformData.map((h, i) => (
                          <div 
                            key={i}
                            style={{ height: `${playingPodcastId === pod.id && isPlaying ? Math.min(100, h + Math.sin(Date.now() / 200 + i) * 20) : h}%` }}
                            className={`flex-1 rounded-t transition-all ${
                              playingPodcastId === pod.id && isPlaying ? 'bg-amber-400' : 'bg-indigo-500/60'
                            }`}
                          ></div>
                        ))}
                      </div>

                      <div className="p-3 bg-slate-900/50 rounded-xl border border-slate-800 text-[11px] text-slate-300 italic">
                        "{pod.transcript}"
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          )}

          {/* TAB 4: MULTI-CHANNEL SYNDICATION */}
          {activeTab === 'syndication' && (
            <div className="space-y-6">
              {/* Active Channels Grid */}
              <div className="space-y-3">
                <h3 className="text-sm font-bold text-white">Active Multi-Channel Syndication Endpoints</h3>
                <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
                  {channels.map(chan => (
                    <div key={chan.id} className="p-4 bg-slate-950 border border-slate-800 rounded-2xl space-y-2">
                      <div className="flex items-center justify-between">
                        <span className="px-2 py-0.5 bg-emerald-500/10 text-emerald-400 border border-emerald-500/30 rounded text-[9px] font-bold">
                          {chan.status}
                        </span>
                        <span className="text-[10px] text-slate-500 font-mono">
                          {chan.type.replace('_', ' ')}
                        </span>
                      </div>
                      <h4 className="text-xs font-bold text-white">{chan.name}</h4>
                      <div className="text-[10px] text-slate-400 flex items-center justify-between pt-1">
                        <span>Subscribers / Audience:</span>
                        <span className="font-bold text-indigo-300">{chan.subscribersCount.toLocaleString()}</span>
                      </div>
                    </div>
                  ))}
                </div>
              </div>

              {/* Live Broadcast Logs */}
              <div className="p-5 bg-slate-950 border border-slate-800 rounded-2xl space-y-4">
                <div className="flex items-center justify-between">
                  <h3 className="text-sm font-bold text-white flex items-center gap-2">
                    <Radio className="w-4 h-4 text-emerald-400" /> Broadcast & Syndication Telemetry Audit Logs
                  </h3>
                  <button
                    onClick={handleBroadcastAll}
                    className="px-3 py-1.5 bg-indigo-600 hover:bg-indigo-500 text-white rounded-xl text-xs font-bold transition-all cursor-pointer"
                  >
                    Trigger Manual Broadcast Now
                  </button>
                </div>

                <div className="divide-y divide-slate-800 font-mono text-xs">
                  {logs.map(log => (
                    <div key={log.id} className="py-3 flex flex-col md:flex-row md:items-center justify-between gap-2">
                      <div className="space-y-0.5">
                        <div className="flex items-center gap-2">
                          <span className="font-bold text-white">{log.channelName}</span>
                          <span className="text-[9px] text-emerald-400 font-bold px-1.5 py-0.5 bg-emerald-500/10 rounded">
                            {log.deliveryStatus}
                          </span>
                        </div>
                        <p className="text-[11px] text-slate-400">{log.articleTitle}</p>
                      </div>

                      <div className="flex items-center gap-4 text-[10px] text-slate-400">
                        <span>Reach: <strong className="text-indigo-300">{log.reachCount.toLocaleString()}</strong></span>
                        <span>Time: {new Date(log.timestamp).toLocaleTimeString()}</span>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          )}

        </div>
      </div>
    </div>
  );
};
